# Generated by Django 5.0.7 on 2024-08-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_app_appname"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="htmlUrl",
            field=models.CharField(
                default="http://f0.0sm.com/node0/2024/08/866ACE1765AB52F8-d8dc519c7d5ac198.jpg",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
