# Generated by Django 5.0.7 on 2024-08-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_app_htmlurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="htmlUrl",
            field=models.TextField(),
        ),
    ]
