# Generated by Django 5.0.7 on 2024-08-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_app_htmlurl"),
    ]

    operations = [
        migrations.CreateModel(
            name="CosConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bucket_name",
                    models.CharField(max_length=255, unique=True, verbose_name="存储桶名称"),
                ),
                ("region", models.CharField(max_length=255, verbose_name="腾讯云区域")),
                (
                    "secret_id",
                    models.CharField(max_length=255, verbose_name="腾讯云 SecretId"),
                ),
                (
                    "secret_key",
                    models.CharField(max_length=255, verbose_name="腾讯云 SecretKey"),
                ),
            ],
            options={
                "verbose_name": "腾讯云 COS 配置",
                "verbose_name_plural": "腾讯云 COS 配置",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
