# Generated by Django 5.0.7 on 2024-08-03 12:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_cosconfig_alter_user_id"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CosConfig",
            new_name="MyCosConfig",
        ),
    ]
