# Generated by Django 5.0.7 on 2024-08-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_rename_cosconfig_mycosconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="NotPrivacyPolicyLink",
            field=models.TextField(default="linkA"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="NotPrivacyPolicyNum",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="UnableToConnectLink",
            field=models.TextField(default="linkB"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="UnableToConnectNum",
            field=models.IntegerField(default="2"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="appPrivacyPolicyLink",
            field=models.TextField(default="linkC"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="appPrivacyPolicyNum",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="notDataInsidePrivacyPolicyLink",
            field=models.TextField(default="linkD"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="notDataInsidePrivacyPolicyNum",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="totalDataNum",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="app",
            name="totalUrlNum",
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
