# Generated by Django 5.0.7 on 2024-08-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_app_notprivacypolicylink_app_notprivacypolicynum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="account",
            field=models.CharField(default="userB", max_length=100),
            preserve_default=False,
        ),
    ]
